Recursively get all dropdown items to support use of wrapper components
TeliaSoneraNorge/styleguide pull request #660
Opened 2020-08-26 11:06 UTC by HeleneGrini

2020-08-28 07:44 UTC, nmenglund requested changes

2020-08-28 07:44 UTC, nmenglund commented on component-lib/src/molecules/Dropdown/Dropdown.stories.tsx
> +storiesOf('Component library|Molecules/Dropdown', module)
Always use `/` as separator in Storybook 6.0 -- i.e. `Component library/Molecules/Dropdown`

2020-08-28 07:44 UTC, nmenglund commented on component-lib/src/molecules/Dropdown/DropdownItem.tsx
> +      itemRef.current.scrollIntoView({ block: 'nearest', inline: 'nearest' });
Tested this in IE11? It seems IE11 only supports the boolean parameter type: https://caniuse.com/#search=scrollIntoView

2020-08-28 07:44 UTC, nmenglund commented on component-lib/src/molecules/Dropdown/DropdownItem.tsx
> +      itemRef.current.scrollIntoView({ block: 'nearest', inline: 'nearest' });
(do we still need to support IE11? maybe put all IE11 polyfills a bucket script somewhere?)

2020-09-01 09:53 UTC, nmenglund requested changes

2020-09-01 09:53 UTC, nmenglund commented on component-lib/src/molecules/Dropdown/useAccessibleDropdown.ts
> +        if (e.keyCode === arrowDown) {
I think the `const` definition is unnecessary; a `// arrow down` comment would suffice

2020-09-01 09:53 UTC, nmenglund commented on component-lib/src/molecules/Dropdown/DropdownItem.tsx
> +   * needs to be handled by the user
I think you should elaborate a little bit in the comment; _what_ isn't supported? _How_ do users need to handle it?

("NB: `scrollIntoView` is not supported properly in IE11`", "needs to be handled by the user with a polyfill")

2020-09-01 14:20 UTC, nmenglund approved these changes

2020-09-02 10:14 UTC, antons1 approved these changes

2020-09-03 08:13 UTC, merged