Create business button
TeliaSoneraNorge/styleguide pull request #691
Opened 2020-09-18 13:28 UTC by mariannemagnussen

2020-09-21 06:56 UTC, antons1 commented
Dette synes jeg også er et godt eksempel på en komponent som er så lik den gamle, at den gamle heller bør tilpasses eller deprecates, heller enn å lage en parallell i business. http://styleguide.channelapi.telia.no/?path=/story/component-library-atoms-buttons--default

2020-09-21 07:07 UTC, mariannemagnussen commented
Hmm ja. Tenkte vel egentlig at denne skal erstatte den gamle på sikt. Lagde også en ny fordi den gamle var blitt unødvendig kompleks (etter min mening da). 

Etter det jeg skjønte skal det ikke være en egen business del av styleguiden, så når denne restruktureringen gjøres vil komponentene i business erstatte de gamle. stemmer ikke det @HeleneGrini  @nmenglund  ?

2020-09-21 07:10 UTC, antons1 commented
Enig i at den gamle er for kompleks, så veldig bra å få bytta den ut. Men forslår å gjøre som @HeleneGrini har gjort med modalen, og markere den gamle som deprecated, og så bare legge denne under den "vanlige" styleguiden.

2020-09-21 07:34 UTC, mariannemagnussen commented
For modal komponenten fikk man ikke kræsj med navngiving, da den gamle het "Modal dialog". Så det vil ikke fungere i dette tilfellet..

2020-09-21 09:30 UTC, mariannemagnussen commented
Todo: Bytte ut gammel Button med denne. Bumpe minor versjon på styleguid. Gi en kort guide til hva som må gjøres hvis noen oppdaterer styleguide.

2020-09-22 09:14 UTC, bogsti commented
Det er en breaking change hvis business button skal bytte ut gammel button.
ser at på vår minside app (b2c mobil) så var det over 150 steder jeg må bytte ut buttons, så det blir en liten jobb.
Så har vi alle de andre appene som også bruker de gamle knappene

Telia.no
Webshop B2C
Webshop B2B
+ Telia bredbånd og Tv (GET apper)  har 6 andre apper som må gjennom.

Vi må nok kordinere litt hvis vi skal få byttet ut, så kanskje den må leve litt i business.

nå som vi skal ha en ny felles b2b2c styleguide, burde vi ikke kanskje diskutere strukturen også
- Hva med monorepos? npm installerer de komponentene man trenger og ikke laste inn hele biblioteket
- StyledComponents? slippe styre med importer av css filer

hva tenker dere? nå har vi jo sjansen til å vurdere dette ...

dist mappa idag er over 15 mb

2020-09-22 10:47 UTC, HeleneGrini requested changes

2020-09-22 10:47 UTC, HeleneGrini commented on src/business/Button/Button.pcss
> +.business-button {
i forrige runde ble vi enige om å prefixe klassenavnene med `telia`, så ville det blitt `telia-business-button`

2020-09-22 10:47 UTC, HeleneGrini commented on src/business/Button/Button.tsx
> +type ButtonProps = {
hva med button compact (den som har litt mindre spacing og font)? En size props, eller en boolean compact props

2020-09-22 10:47 UTC, HeleneGrini commented on src/business/Button/Button.tsx
> +          className={cs('business-button--icon', {
her tenker jeg klassenavnet bare burde være `business-button-icon` (men enkel dash før icon), ihht. BEM metoden. icon er et element, ikke en modifier. 
--right og --ball er derimot modifiers, så der er dobbel dash riktig 👍

2020-09-22 10:47 UTC, HeleneGrini commented on src/business/Button/Button.tsx
> +        [`business-button--${type}`]: type,
siden du defaulter type kan  vel `business-button--${type}` bare være input til cs, uten ekstra logikk på om type er definert 
```
cs('business-button',  business-button--${type} , { .. })

2020-09-22 11:16 UTC, mariannemagnussen commented on src/business/Button/Button.pcss
> +.business-button {
kan egentlig bare kalle den telia-button da ? 😃

2020-09-22 11:41 UTC, nmenglund commented on src/business/Button/Button.tsx
> +  type?: ButtonType;
Bør unngå å bruke `type` som prop siden den er så innarbeidet på button type (button,submit) -- kan vi evt. bruke "kind" på samme måte som i den eksisterende knappen?

2020-09-22 11:51 UTC, mariannemagnussen commented on src/business/Button/Button.tsx
> +  type?: ButtonType;
Ja 👍

2020-09-23 12:52 UTC, mariannemagnussen commented on src/business/Button/Button.stories.tsx
> +    <h3>Compact button</h3>
Null stress! Hvis du tror det trengs kan vi godt legge inn det

2020-09-24 06:42 UTC, HeleneGrini approved these changes

2020-09-24 10:32 UTC, HeleneGrini approved these changes

2020-09-24 10:40 UTC, nmenglund requested changes

2020-09-24 10:40 UTC, nmenglund commented on src/business/Button/Button.tsx
> +        [`telia-button--${kind}--disabled`]: href && disabled,
Trenger vi å ta med `${kind}` her? Blir vel ryddigere å bare ha `.telia-button--disabled`. Der vi må ha begge delere pga. spesifisitet/presedens i CSS kan man definere begge; i.e. `.telia-button-primary.telia-button--disabled { ... }`

2020-09-24 10:40 UTC, nmenglund commented on src/business/Button/Button.tsx
> +  const Tag: any = href ? 'a' : 'button';
Kan vi unngå `any` her? (i en ideell fremtid vil vi skru `any` helt av)

2020-09-24 10:40 UTC, nmenglund commented on src/business/Button/Button.tsx
> +        'telia-button--ball--compact': !!size && icon && !label,
Samme med denne; kan vi kombinere disse to i CSS i stedet for å definere en helt ny klasse? i.e.  `.telia-button--ball.telia-button--compact`

2020-09-24 10:40 UTC, nmenglund commented on src/business/Button/Button.tsx
> +            'telia-button-icon--right': iconRight,
Og disse også; jeg synes det blir ryddigere av kombinere disse i CSS;
`.telia-button--ball > .telia-button-icon {`
i stedet for `.telia-button-icon--ball {`

2020-09-24 10:44 UTC, nmenglund requested changes

2020-09-24 10:44 UTC, nmenglund commented on src/business/Button/Button.tsx
> +  size?: 'compact';
Her er det ryddig å ta med `default` også av dokumentasjonshensyn; når man bruker Button uten å kjenne komponenten allerede er det veldig fint å se allerede i editorens autocomplete hvilke alternativer vi har

2020-09-24 10:44 UTC, nmenglund commented on src/business/Button/Button.tsx
> +  kind?: ButtonKind;
Alle disse prop'ene er ganske selvforklarende, men jeg synes likevel det er god praksis (og det setter en god presedens) å ta med en docblock for de fleste prop'ene, og gi litt mer info om betydningen for helt å unngå noen tvetydigheter

2020-09-24 10:44 UTC, nmenglund commented on src/business/Button/Button.tsx
> +  href?: string;
F.eks. her; _If `href` is specified, the Button will be rendered using an `<a>` element._ eller noe sånt

2020-09-24 11:18 UTC, mariannemagnussen commented on src/business/Button/Button.tsx
> +        [`telia-button--${kind}--disabled`]: href && disabled,
Nei, må vel ikke ha det, fikser

2020-09-24 19:22 UTC, nmenglund approved these changes
:ok_hand:

2020-09-25 05:34 UTC, merged