declare className prop in all FullWidthTable components
TeliaSoneraNorge/styleguide pull request #693
Opened 2020-09-22 14:35 UTC by ropimo

The className prop was not declared in the FullWidthTable components. This PR should fix it.
This changes might affect all sites. I hope it doesn't break anything. Please verify it works.

I also added some Storybook knobs for it (and the white footer, to reduce code)

2020-09-22 14:36 UTC, ropimo commented
<img width="1004" alt="Screenshot 2020-09-22 at 16 14 40" src="https://user-images.githubusercontent.com/29574833/93896909-c7586b80-fcf1-11ea-9444-1c6afeac0201.png">

2020-09-24 19:33 UTC, nmenglund requested changes

2020-09-24 19:33 UTC, nmenglund commented on src/atoms/FullWidthTable/FullWidthTable.stories.pcss
> +.purple {
All .pcss files will be merged into the same, standard distribution bundle in the same shared CSS namespace (also in the npm package).

For stories, I suggest we avoid .pcss files altogether, and use inline styles where we need them (alternatively a shared, storybook-specific .pcss that's explicitly excluded from the main distribution)

2020-09-24 19:33 UTC, nmenglund commented on src/atoms/FullWidthTable/FullWidthTable.stories.tsx
> +  const column2classNames = optionsKnob(
Might replace this with something like `const styles = { purple: { color: colors.corePurple }, italic: { fontStyle: 'italic'; },` etc.
and use the option as lookup key?

2020-09-24 19:33 UTC, nmenglund commented on src/atoms/FullWidthTable/FullWidthTable.stories.tsx
> +          <Th className={column2classNames}>Column 2</Th>
`<Th styles={selectedStyle}>` instead?

2020-09-24 19:33 UTC, nmenglund commented on src/atoms/FullWidthTable/FullWidthTable.d.ts
> +  className?: string;
`styles={}` might be useful here too?

2020-09-24 19:33 UTC, nmenglund commented on src/atoms/FullWidthTable/FullWidthTable.d.ts
> +  Th: React.FC<CommonProps>;
Will using only CommonProps cause a TS error if we use plain <th> attributes on `<Th>` (do we _want_ to be able to use any other generic attributes on `<Th>`?

2020-09-30 06:20 UTC, ropimo commented on src/atoms/FullWidthTable/FullWidthTable.stories.pcss
> +.purple {
Good catch. I will see what can I do to avoid leaking the storybook only styles to the main distribution

2020-09-30 06:24 UTC, ropimo commented on src/atoms/FullWidthTable/FullWidthTable.stories.tsx
> +          <Th className={column2classNames}>Column 2</Th>
The point of this PR is to accept className styles defined as CSS classes, instead of inline styles. That's why I am using the **className** (which is **class** in pure HTML)

2020-09-30 06:40 UTC, ropimo commented on src/atoms/FullWidthTable/FullWidthTable.d.ts
> +  className?: string;
yes, sure. And `id?: string;` let me see if I find a more generic React HTML attributes type

2020-09-30 06:45 UTC, ropimo commented on src/atoms/FullWidthTable/FullWidthTable.d.ts
> +  Th: React.FC<CommonProps>;
Before they were defined as: `Th: React.FC<React.ReactNode>;` I wasn't sure of the value of doing so. Have we **lost** any accepted attributes with these PR changes?

2020-09-30 06:47 UTC, ropimo commented on src/atoms/FullWidthTable/FullWidthTable.stories.tsx
> +  const column2classNames = optionsKnob(
`optionsKnob` is the StoryBook knob which allows multiple selections. Nor sure I understand what you mean.

2020-09-30 07:08 UTC, ropimo commented on src/atoms/FullWidthTable/FullWidthTable.d.ts
> +  className?: string;
I'm inclined for this:
`declare type CommonProps = React.HTMLAttributes<HTMLElement>;`

2020-09-30 07:09 UTC, ropimo commented on src/atoms/FullWidthTable/FullWidthTable.d.ts
> +  Th: React.FC<CommonProps>;
I think this will be the most generic way to solve it:
`declare type CommonProps = React.HTMLAttributes<HTMLElement>;`

2020-09-30 09:50 UTC, ropimo commented on src/atoms/FullWidthTable/FullWidthTable.stories.pcss
> +.purple {
By using .css instead of .pcss the styles will NOT end up in the generated Telia Styleguide final CSS

2020-10-06 08:50 UTC, nmenglund requested changes

2020-10-06 08:50 UTC, nmenglund commented on src/atoms/FullWidthTable/FullWidthTable.stories.tsx
> +          <Th className={column2classNames}>Column 2</Th>
Ah, I made a suggestion that wasn't particular to this PR -- my suggestion was to avoid className altogether so we could avoid an external .css file. This is fine!

2020-10-06 08:50 UTC, nmenglund commented on src/atoms/FullWidthTable/FullWidthTable.stories.tsx
> +    <FullWidthTable id={'defaultFullWidthTable'} className={'no-ts-error'}>
Prefer quoted strings over `{}` expressions when providing static strings as props ( `id="defaultFullWidthTable" className="no-ts-error"`)

2020-10-06 08:50 UTC, nmenglund commented on src/atoms/FullWidthTable/FullWidthTable.stories.tsx
> +  const column2classNames = optionsKnob(
Related to the other comment, I meant continuing to use `optionsKnobs`, but provide a map of inline styles instead of classes. This (like the other comment) was a suggestion to avoid using a separate .css file. But this is fine now :+1:

2020-10-06 08:50 UTC, nmenglund commented on src/atoms/FullWidthTable/FullWidthTable.d.ts
> +declare type CommonProps = React.HTMLAttributes<HTMLElement>;
Instead of a shared `CommonProps`, we can add the element-specific attributes to each element, e.g.:

```
declare type ThSortableProps = React.ThHTMLAttributes<HTMLTableHeaderCellElement> & { isSorted?: boolean; };
```

etc.

2020-10-06 08:50 UTC, nmenglund commented on src/atoms/FullWidthTable/FullWidthTable.d.ts
> +  onSort: () => void;
Should `onSort` be optional here? Even in cases where it doesn't make sense to leave out a event handler, I often prefer making it optional to avoid having to fill it out with a temporary value during development

2020-10-06 09:18 UTC, ropimo commented on src/atoms/FullWidthTable/FullWidthTable.d.ts
> +  onSort: () => void;
Making it optional would make it semantically incorrect, and therefore misleading. I strongly suggest you not making the props optional if they are mandatory. You can always add a `// @ts-ignore` on your client code if you don't want to use the advantages of a typed system.

2020-10-06 09:28 UTC, ropimo commented on src/atoms/FullWidthTable/FullWidthTable.stories.tsx
> +    <FullWidthTable id={'defaultFullWidthTable'} className={'no-ts-error'}>
I do prefer consistency myself and always using `attribute={***}` in the React code. But I will adapt it to the project standard.

2020-10-06 09:30 UTC, ropimo commented on src/atoms/FullWidthTable/FullWidthTable.d.ts
> +declare type CommonProps = React.HTMLAttributes<HTMLElement>;
I considered it myself, but I thought it was giving very little value, and was enough to make the previous code correct. But you are right, it's even more precise this way, so I will change it.

2020-10-06 10:21 UTC, nmenglund commented on src/atoms/FullWidthTable/FullWidthTable.d.ts
> +  onSort: () => void;
Oh, come on now -- this is _not_ about not using the advantages of a typed system.

More along the lines of a `Button` -- its primary function is to be clicked, and it is rather pointless without an `onClick` (not taking HTML/forms into account here). Still, allowing for `onClick` to be not present or undefined reduces friction during development; for example if I want to place the button and test the layout before implementing the click handler. Or if I want to propagate a function that might be undefined from the "outside" into the event handler.

I often shamelessly prefer being pragmatic over being entirely semantically correct. I much prefer `{ isSorted?: boolean; isSortedDesc?:boolean; sortPriority?: number; }` over elaborate and cumbersome types that correctly define all valid combinations of props (e.g. prevent `isSortedDesc`,`sortPriority` from being provided when `isSorted` is false).

While this is an interesting point of discussion, I'm happy about the PR either way :)

2020-10-06 10:23 UTC, nmenglund approved these changes

2020-10-06 10:29 UTC, merged