Add avatar component
TeliaSoneraNorge/styleguide pull request #694
Opened 2020-09-23 12:52 UTC by HeleneGrini

2020-09-23 15:46 UTC, nmenglund requested changes

2020-09-23 15:46 UTC, nmenglund commented on src/molecules/Avatar/Avatar.tsx
> +  compact?: boolean;
Bør være `size="compact"` i stedet? (gjelder også button, forsåvidt)

2020-09-23 15:46 UTC, nmenglund commented on src/molecules/Avatar/Avatar.pcss
> +.telia-avatar--compact {
Bør vise compact i storybook

2020-09-23 15:46 UTC, nmenglund commented on src/molecules/Avatar/Avatar.pcss
> +  background-color: #f2f2f2;
Bør definere font-size -- uten default font-size blir arvet størrelse forskjellig avhengig av om den arver for default/href eller fra button

2020-09-23 15:46 UTC, nmenglund commented on src/molecules/Avatar/Avatar.tsx
> +} & (
Kan bare ha `href?: string;` her?

2020-09-24 06:43 UTC, HeleneGrini commented on src/molecules/Avatar/Avatar.pcss
> +.telia-avatar--compact {
Har en story for compact også, hvis det var det du mente?

2020-09-24 06:47 UTC, nmenglund commented on src/molecules/Avatar/Avatar.pcss
> +.telia-avatar--compact {
Ah, my bad -- så ikke at det var en egen story. Når det er sagt er det kanskje greit å klemme inn alt sammen på én story når komponenten er så liten? :)

2020-09-24 09:32 UTC, antons1 approved these changes

2020-09-24 10:26 UTC, nmenglund approved these changes

2020-09-24 12:49 UTC, merged