Style modals for mobile
TeliaSoneraNorge/styleguide pull request #701
Opened 2020-10-05 07:07 UTC by HeleneGrini

2020-10-05 07:50 UTC, mariannemagnussen requested changes

2020-10-05 07:50 UTC, mariannemagnussen commented on src/molecules/Modal/ModalBody.tsx
> +  noPadding?: boolean;
Er det på mobil man ikke ønsker padding?  Eller når ønsker man å benytte denne?
(Hvis det er på mobil kan den vel ligge under @media (max-width: 600px) ) 🤔

2020-10-05 09:25 UTC, HeleneGrini commented on src/molecules/Modal/ModalBody.tsx
> +  noPadding?: boolean;
Tanken var egentlig å støtte det uavhengig av skjermstørrelse. Til når man trenger at innholdet skal ta full bredde

2020-10-06 06:55 UTC, mariannemagnussen commented on src/molecules/Modal/ModalBody.tsx
> +  noPadding?: boolean;
Okei. Sliter litt med å se behovet for det 😅  For man vil vel aldri at tekst eller andre ting skal gå heelt ut i kanten 🤔

2020-10-06 06:55 UTC, mariannemagnussen approved these changes

2020-10-06 07:02 UTC, HeleneGrini commented on src/molecules/Modal/ModalBody.tsx
> +  noPadding?: boolean;
Det eksempelet som dukket opp nå var en modal meny som skulle ha en liste med knapper som tar full bredde -- `Mobile Menu` her f.eks https://www.figma.com/file/18YcIatgcizcggCAeU4I7n/Navigation?node-id=2%3A2 

Så jeg tenkte bare vi kunne støtte det generelt (for desktop og mobil), men er for så vidt enig i det du sier om at det trolig ikke  kommer til å være så mange tilfeller 🤷‍♀️

2020-10-06 07:06 UTC, mariannemagnussen commented on src/molecules/Modal/ModalBody.tsx
> +  noPadding?: boolean;
Ahaa, da henger jeg med!  Fint å gjøre det mer generelt 👌

2020-10-06 09:36 UTC, merged