Feature/business list
TeliaSoneraNorge/styleguide pull request #704
Opened 2020-10-06 14:46 UTC by antons1

List based on https://www.figma.com/file/F17hx618VP6G3owzDCz88M/List-Cards?node-id=65%3A105

2020-10-07 06:18 UTC, HeleneGrini requested changes

2020-10-07 06:18 UTC, HeleneGrini commented on src/business/List/List.tsx
> +      'telia-listItem--heading': !compact,
hva med noe sånt? 
```
 className={cn('telia-listItem telia-listItem__heading', {
      'telia-listItem__heading--compact': compact, })
```
Så slipper vi logikk på begge. 
det er jo alltid en header, som noen ganger er compact?

2020-10-07 06:18 UTC, HeleneGrini commented on src/business/List/List.tsx
> +import React from 'react';
Jeg synes det er lettere å få oversikt når disse komponentene er splittet i egen mapper. Blir litt vanskelig å følge alt som skjer i denne fila imo

2020-10-07 06:18 UTC, HeleneGrini commented on src/business/List/List.tsx
> +  itemName: string;
`label` kanskje, for å være konsekvent i naming. Har inntrykk av det er det vi har gått for i andre komponenter

2020-10-07 06:18 UTC, HeleneGrini commented on src/business/List/List.tsx
> +      <div className="telia-listItem__mainContent">
bare content holder kanskje når ikke det er flere content blocks ?

2020-10-07 06:18 UTC, HeleneGrini commented on src/business/List/List.stories.tsx
> +export default {
Ser ingen stories på kompakte kort, men ser ut som du har laget støtte for det i koden. 

Kanskje også få inne nonen stories med klikkbare items?

2020-10-07 06:18 UTC, HeleneGrini commented on src/business/List/List.pcss
> +  justify-content: space-between;
denne er ikke støttet i IE. Tenker det er greit, siden IE ikke støttes lengre. Men burde vi kommentere slike ting, for å dokumentere at det er et bevisst valg? Bare et spørsmål

2020-10-07 09:26 UTC, antons1 commented on src/business/List/List.pcss
> +  justify-content: space-between;
Støttes i IE11 iflg https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content men har ikke sjekka noen andre kilder. Kan godt legge inn en kommentar. På den annen side, siden vi har bestemt at vi ikke støtter IE11, så vet jeg ikke om kommentar er nødvendig? Eventuelt kunne vi lagt det inn i readmeen eller introsiden. Jeg sjekka nettopp, og det er flere ting i den lista som ikke funker helt i IE11, så sånn sett tenker jeg at folk som skal bruke styleguiden bare må anta at den ikke er laget for å støtte IE

2020-10-07 14:11 UTC, HeleneGrini requested changes

2020-10-07 14:11 UTC, HeleneGrini commented on src/business/List/BaseListItem.tsx
> +    <li
hvis denne har en onClick så burde den også få tabIndex=0 og role='button' for å gjøre den accessible. 

Og så sette focus style ihht. skissene 👍

2020-10-08 09:10 UTC, mariannemagnussen commented
Nå er jo jeg ganske fersk i styleguiden, men merka jeg brukte ganske lang tid på å sette meg inn i denne..  Smud med lite kode, men av og til kan det kanskje bli litt for lite - lite lesbart. Nå er det kanskje ikke så mange som skal inn og fikse noe i denne, men tenker terskelen kan bli litt høy når koden blir så kompakt 😅     

Lurer forresten på om man trenger den context'en i BaseListItem?
```
const { decorator, label, description, caption, onClick, compact, underlined, card, shadow, dark, flat, none } = {
    ...(containsStyleProps(props) ? props : { ...props, ...context }),
  };
```
 Kan man ikke bare hente direkte fra props?
```
const { decorator, label, description, caption, onClick, compact, underlined, card, shadow, dark, flat, none } = props;
```

At listeelementene er ulike er vel ikke et krav? 🤔  Som regel lager man jo lister med iterator..  
Og i de få tilfellen kan vi bruke css til å endre det 😃 

Ellers syns jeg listene så veldig bra ut! 🤩

2020-10-08 09:37 UTC, antons1 commented
Jo, det er sant det. Årsaken til at den er der er at jeg tenkte det var greit å kunne spesifisere utseendet til lista i `List`, og slippe å sette det på de individuelle `ListItems`, og så gir det fortsatt mulighet til å overstyre det som er satt i `List` ved å sette props på `ListItems`. Men ser at det kan hende kompleksiteten ikke går over nytten, så kan legge inn en kommentar som forklarer, eller fjerne hele contexten - stemmer for/mot en av dem? @mariannemagnussen @nmenglund @HeleneGrini

2020-10-08 13:59 UTC, HeleneGrini commented
Enig 3,

2020-10-08 14:09 UTC, HeleneGrini commented
Enig i at det tilfører endel ekstra kompleksitet og koden blir litt vanskelig å følge, men ser også at det er litt nyttig å kunne sette en generell style for hele lista. Hvis vi velger at vi skal støtte det tenker jeg dog at det kanskje burde gjøres i css-en? At vi setter klassenavn på lista,  og sier at alle list items som er children av f.eks telia-list--dark skal ha dark style, uten den programmatiske delen av å eksplisitt sette klassenavnene på itemsene?  Da kan vi fjerne konteksten, og bevare funksjonaliteten. Tror også det er innafor om vi må style på list-items, og ikke kan gjøre det generelt på list, men jeg er åpen for begge deler

2020-10-12 10:03 UTC, antons1 commented
Da fikser jeg det, og så merger jeg

2020-10-12 13:22 UTC, antons1 commented
Etter å ha prøvd å skrive om CSSen tror jeg ikke det er en så god idé likevel. Det er vanskelig å skrive CSS-regler for list som skal sette en standard på listItem, men som skal overskrives hvis listItem får egne stiler, uten at det blir en hel haug med veldig spesifikke selectors i begge stilene - dvs CSSen blir veldig komplisert hvis listItem skal arve stilene. Så jeg foreslår å enten beholde funksjonaliteten som den er, eller kreve at stilen blir satt på hvert av itemene. For min del synes jeg det fungerer som det er.

2020-10-12 13:27 UTC, mariannemagnussen commented
Hvis det var opp til meg ville jeg nok forenklet koden.  item'ene i en liste lages jo (nesten) alltid med en map funksjon, så da er det ikke noe stor jobb å sette stilen på den i stedet for på lista.  Meen skal ikke være vanskelig på det, så hvis du foretrekker det sånn det er nå går det fint 👌

2020-10-12 14:02 UTC, HeleneGrini approved these changes

2020-10-12 14:04 UTC, HeleneGrini commented
Enig med Marianne i at jeg kanskje ville foretrukket enklere kode. Men det funker veldig smud og begge deler er greit for min del! Så godkjent herfra, og opp til deg @antons1  🚀

2020-10-13 09:05 UTC, merged