Add business textfield
TeliaSoneraNorge/styleguide pull request #725
Opened 2020-10-27 14:27 UTC by HeleneGrini

Figma sketches: https://www.figma.com/file/DY2nAi4QVg4DZWQSGP1A0n/Text-field?node-id=2%3A2
**Should replace existing text field in the not so distant future.** 

TODO: update the Dropdown with search, and add styles and documentation for "quick search"  https://www.figma.com/file/EBjS8URGPnFXU0SQsVL9la/Quick-search?node-id=2%3A2

2020-10-27 15:12 UTC, mariannemagnussen requested changes
Veldig nice! 🤩   Noe pirk bare:

Så kjapt på det, klarte ikke finne ut av hvorfor, men alle feltene unntatt det i midten har litt høyere tekst, altså teksten er et par pixler fra å være sentrert 😅 
<img width="1061" alt="Screenshot 2020-10-27 at 16 03 08" src="https://user-images.githubusercontent.com/17473615/97321279-fd4bbb00-186e-11eb-9bdd-6fe5a63d898f.png">

2020-10-27 15:17 UTC, HeleneGrini commented on src/business/TextField/TextField.tsx
> +   * The helpe text content displayed under the input
😂  må ha med litt typos 🙃

2020-10-27 15:18 UTC, HeleneGrini commented on src/business/TextField/TextField.tsx
> +   * The helpe text content displayed under the input
Good catch på det med høyden! Skal undersøke 🕵️

2020-10-28 06:44 UTC, mariannemagnussen approved these changes

2020-10-28 08:42 UTC, merged