Add Chip component
TeliaSoneraNorge/styleguide pull request #737
Opened 2020-11-02 09:57 UTC by mariannemagnussen

2020-11-02 10:58 UTC, HeleneGrini requested changes
Ser ut til at det er litt mye padding. skal være 6px 16px ihht skissene. Ser også ut til at det ikke er noen hover-state når en chip er aktiv. Det skal det kanskje være? 🤔

2020-11-02 10:58 UTC, HeleneGrini commented on src/molecules/Chip/Chip.tsx
> +          grey: kind === 'grey',
kanskje heller ta telia-chip__active, telia-chip__disabled, telia-chip__grey for å følge samme mønster som de andre komponentene?  (angåene grey-klassen så blir vel den uansett satt av   `telia-chip--${mode}`?

2020-11-02 10:58 UTC, HeleneGrini commented on src/molecules/Chip/Chip.tsx
> +      {mode === 'input' && <Button kind="secondary-text" icon="close" onClick={() => onClick} disabled={disabled} />}
onClick her vil ikke bli kalt --  endre til `onClick={onClick}`

2020-11-02 10:58 UTC, HeleneGrini commented on src/molecules/Chip/Chip.tsx
> +      onClick={(e: any) => {
Kan vi unngå å caste til any her?

2020-11-02 11:11 UTC, mariannemagnussen commented on src/molecules/Chip/Chip.tsx
> +          grey: kind === 'grey',
Åja, kan gjøre det ja!  Fulgte ikke det mønsteret på Button 😬

2020-11-02 11:59 UTC, mariannemagnussen commented on src/molecules/Chip/Chip.tsx
> +      onClick={(e: any) => {
Har du forslag til hvordan? Hvis jeg bare har (e) får man rød strek i fila

2020-11-02 12:03 UTC, mariannemagnussen commented on src/molecules/Chip/Chip.tsx
> +      onClick={(e: any) => {
Endret parameter definisjonen på onClick sånn at den ikke har med event. Er det greit ?

2020-11-02 12:04 UTC, mariannemagnussen commented
Hvilken chip mener du ikke har hover effekter? For fra skissene skulle choice chip med white mode bare ha mørkere tekst og bittelitt mørkere background color🤔

2020-11-02 13:21 UTC, HeleneGrini commented on src/molecules/Chip/Chip.tsx
> +          grey: kind === 'grey',
Nesten da, bare med -- i stedet for __ 😄

2020-11-02 14:40 UTC, HeleneGrini commented
Jeg mener når en chips er aktiv "Actie state" i storybook, så er det ingen hover-effekt og det tenker jeg kanskje det burde være. Ser at skissene ikke sier noe konkret om det, ville kanskje hørt med ux-eieren av denne 😄 En liten ting til --- ser at cursoren ikke blir en pointer på `input-chip`

2020-11-02 15:00 UTC, mariannemagnussen commented
ahaa, når den lilla (altså active choice chip) hovres?  Jeg er litt usikker på om den skal ha det, siden det er en choice chip. Så den vil typisk brukes som en slags "radio button aktig" chip..   Så når den er valgt er den på en måte valgt. Mulig man skal kunne trykke igjen for å fjerne det da. kan høre med designer!

Det er bare close-knappen som har cursor=pointer. Syns du hele skal ha det? Og skal hele fungere som et close i så fall?

2020-11-02 15:27 UTC, HeleneGrini commented
I begge tilfellene, choice og input, så kan hele få focus, og hele har enten cursor eller hover effekt, så da forventer jeg at man skal kunne klippe på de. Hvis det ikke er tilfellet så må vi jo heller fjerne indikasjonene på at den kan klikkes, fremfor å gjøre den mer tilgjengelig 😄  Ta en prat med UX i morgen. Vi kan også gjerne ta en prat før/etter du snakker med UX 😊

2020-11-03 09:07 UTC, HeleneGrini approved these changes

2020-11-03 09:19 UTC, merged