Adjustments to business table
TeliaSoneraNorge/styleguide pull request #747
Opened 2020-11-06 13:55 UTC by HeleneGrini

- Handle selectable and clickable rows 
- support fixed width 
- support skeleton loading 
- support connected rows

2020-11-06 14:26 UTC, mariannemagnussen requested changes
Paging knappene er alltid disabled 🤔

2020-11-06 18:36 UTC, mariannemagnussen requested changes
Den indeterminate checkboxen fungerer motsatt av sånn den gjør på min portal. Her velger den alle når man trykker på den, mens der fjerner den alle. Min portal måten føles mer riktig siden checkboxen har et minustegn synes jeg. Hva tenker du?

Ellers ser det bra ut! 😄

2020-11-06 18:36 UTC, mariannemagnussen commented on src/business/Table/Table.pcss
> +      left: 25%;
Hvis vi på sikt ønsker ikoner på radene, sånn som i min portal, så må jo denne være 0 for at streken skal bli mellom ikonene. Enig i at det er finere sånn det er nå hvis det bare er tekst da. Så kanskje bare overskrive for tabellene i one portal? 🤔  Virker voldsomt å ta inn en prop bare for det.. Kanskje man kan ha med en stil for .data-table_cell og .icon som overskriver left?

2020-11-09 06:34 UTC, HeleneGrini commented
Hvordan indeterminate-checkboxen oppfører seg ligger utenfor tabell komponenten --  det er brukerens ansvar å si hva som skal skje onChange på checkboxene. Men kan endre storyen til å gjenspeile den oppførselen man burde bruke 👍 

Angående connected stilen så er jeg enig i at det er litt voldsomt å ta inn en prop for det. Kan se på om det er ryddig å lage en <ConnectRow/> components som kan tilpasses litt lettere? Som man kan plasseres mellom de radene som er connected

2020-11-09 07:09 UTC, HeleneGrini commented
Droppen en egen komponent for connected rows, da det ikke er lov med divs inni en tabell, men defaultet til å aligne med en avatar i første celle

2020-11-09 07:25 UTC, mariannemagnussen requested changes

2020-11-09 07:25 UTC, mariannemagnussen commented on src/business/Table/Table.pcss
> +.data-table__row--connected.data-table__row--selected {
Denne skjønte jeg ikke helt..  Så prøvde å legge inn connected på en selected table.  Det som skjedde da var at streken er mellom checkboxene, men så flytter den seg til navnet hvis jeg krysser av checkboxen til den siste connected 🤔

2020-11-09 07:31 UTC, HeleneGrini commented on src/business/Table/Table.pcss
> +.data-table__row--connected.data-table__row--selected {
😄  tanken var å flytte den ett hakk inn når tabellen er selectable, men testet ikke det du sier der! Jeg fjerner det, og setter den på første celle. Så får man bare overskrive stylen ved behov?

2020-11-09 07:34 UTC, mariannemagnussen approved these changes

2020-11-09 07:46 UTC, merged