PreventDefault on dropdownitem event
TeliaSoneraNorge/styleguide pull request #755
Opened 2020-11-10 14:40 UTC by mariannemagnussen

2020-11-10 15:00 UTC, HeleneGrini requested changes

2020-11-10 15:00 UTC, HeleneGrini commented on src/molecules/Dropdown/Dropdown.stories.tsx
> +            <Dropdown open={true}>
Synes kanskje vi skal håndter open staten og legge inn en lukk knapp i storyen for å illustrer use-caset for noe sånt som dette. Hva tenker du?

2020-11-10 15:02 UTC, mariannemagnussen commented on src/molecules/Dropdown/Dropdown.stories.tsx
> +            <Dropdown open={true}>
Ja, det kan jo være greit for andre som skal ha noe lignende. og det er det helt sikker noen som skal ha 😄

2020-11-11 10:43 UTC, HeleneGrini requested changes
par småting og et spørsmål 😊

2020-11-11 10:43 UTC, HeleneGrini commented on src/molecules/Dropdown/Dropdown.stories.tsx
> +          <DropdownItem onClick={() => setSelected((prevState) => ({ ...prevState, item1: !prevState.item1 }))}>
trenger ikke bruke prevState her? 

```
setSelected({ ...state, item1: !state.item1 })>

2020-11-11 10:43 UTC, HeleneGrini commented on src/molecules/Dropdown/Dropdown.stories.tsx
> +import { Checkbox, Button } from '../../business';
👌  nais!

2020-11-11 10:43 UTC, HeleneGrini commented on src/molecules/Dropdown/context.ts
> +   * Toggle dropdown menu open/close
... on click dropdown item 

legge det til i kommentaren?

2020-11-11 10:43 UTC, HeleneGrini commented on src/molecules/Dropdown/Dropdown.stories.tsx
> +            <Button label="Save" size="compact" onClick={() => setOpen((prevState) => !prevState)} />
samme her 
```
setOpen(!state)

2020-11-11 10:43 UTC, HeleneGrini commented on src/molecules/Dropdown/Dropdown.stories.tsx
> +          <DropdownItem>
la merke til at det er hover på dropdownItem selv om den ikke har onClick. Ikke relatert til denne pr-en egentlig, men hva synes du? Skal vi ha det uansett, eller skal vi si at der er hover klikkbar hvis den er klikkbar? 

Item blir også rendret som en knapp, selv om vi ikke har en onClick og itemToggle  --  det burde vi fikse. Kan ta disse tingene i en egen pr

2020-11-11 10:57 UTC, mariannemagnussen commented on src/molecules/Dropdown/context.ts
> +   * Toggle dropdown menu open/close
ops, yess

2020-11-11 11:14 UTC, mariannemagnussen commented on src/molecules/Dropdown/Dropdown.stories.tsx
> +          <DropdownItem>
For de med checkbox syns jeg det er fint at man kan trykke hvor som helst i listeelementet. og tenker det vil se rart ut hvis det ikke er noen hover effekter, men så kan man trykke likevel 🤔

2020-11-11 11:17 UTC, HeleneGrini commented on src/molecules/Dropdown/Dropdown.stories.tsx
> +          <DropdownItem>
men onClicken er jo på elementet når vi har checkbox da, så det vil bli riktig

2020-11-11 11:20 UTC, mariannemagnussen commented on src/molecules/Dropdown/Dropdown.stories.tsx
> +          <DropdownItem>
ja, det er det.  Da syns jeg vi skal ta bord hover effects :D

2020-11-11 12:46 UTC, HeleneGrini requested changes

2020-11-11 12:46 UTC, HeleneGrini commented on src/molecules/Dropdown/DropdownItem.tsx
> +          'telia-dropdown-item--noHover': !props.onClick,
!props.onClick  && !itemToggle

2020-11-11 12:46 UTC, HeleneGrini commented on src/molecules/Dropdown/Dropdown.pcss
> +    pointer-events: none;
nå blir det ikke mulig å klikke på den i det heletatt. 

Enten så kan vi si 
```

&--noHover:hover  {
   cursor: auto; (eller hva som blir riktig)
   background-color: var(--white);
}
```

eller så tenker jeg vi kan ha en klasse 
```
'telia-dropdown-item__clickable': Tag === 'button' (eller props.onClick || toggleItem
```
og så flytter vi hover staten i css-en inn i den klassen

2020-11-11 12:46 UTC, HeleneGrini commented on src/molecules/Dropdown/DropdownItem.tsx
> +          'telia-dropdown-item--noHover': !props.onClick,
kanskje lage en conts isClickable ?

2020-11-11 12:46 UTC, HeleneGrini commented on src/molecules/Dropdown/DropdownItem.tsx
>        onClick={onClick}
kanskje her si ` onClick={isClickable ? onClick : undefined}` ? det fikser et issue med highlight index som vi får hvis vi sender med en onClick på noe som ikke kan klikkes på

2020-11-11 12:47 UTC, HeleneGrini commented on src/molecules/Dropdown/Dropdown.pcss
> +    pointer-events: none;
kan bruke consten isClickable her også hvis du lager den

2020-11-11 13:14 UTC, HeleneGrini requested changes

2020-11-11 13:14 UTC, HeleneGrini commented on src/molecules/Dropdown/Dropdown.pcss
> +  &__active,
denne funker ikke.. .telia-dropdown-item__clickable__active er ikke en klasse. 

Active og focus style kan ligge direkte under .telia-dropdown-item (vil aldri få focus, eller bli aktiv med mindre man kan klikke), og det vil fikse problemet. Evt må du legge til en block

`.telia-dropdown-item__clickable.telia-dropdown-item__active` stemmer kanskje for å flytte focus og active inn i .telia-dropdown-item

2020-11-11 13:22 UTC, mariannemagnussen commented on src/molecules/Dropdown/Dropdown.pcss
> +  &__active,
Jeg tror jeg må gå for en block?
For den får active prop selv om den ikke er clickable  🤔

2020-11-11 13:26 UTC, HeleneGrini commented on src/molecules/Dropdown/Dropdown.pcss
> +  &__active,
Okei, gjør det! 👍

2020-11-11 13:38 UTC, HeleneGrini commented on src/molecules/Dropdown/DropdownItem.tsx
>        role={props.href ? 'link' : 'button'}
det blir satt role 'button' selv om den ikke er klikkbar

2020-11-11 14:09 UTC, HeleneGrini commented on src/molecules/Dropdown/DropdownItem.tsx
> +      role={isClickable ? (props.href ? 'link' : 'button') : 'div'}
fallback til undefined i stedet for 'div'

2020-11-11 14:13 UTC, HeleneGrini approved these changes

2020-11-11 14:17 UTC, HeleneGrini approved these changes

2020-11-11 14:18 UTC, merged