Add expandable and open properties for listItem
TeliaSoneraNorge/styleguide pull request #831
Opened 2020-12-08 10:06 UTC by mariannemagnussen

2020-12-08 11:19 UTC, HeleneGrini commented on src/business/List/List.pcss
>      padding: 1.25rem 1.5rem;
Tror denne mp settes på mainWrapper

2020-12-08 11:22 UTC, HeleneGrini commented on src/business/List/List.pcss
> +.telia-listItem__mainWrapper {
tror vi må sette border-radius her når det er inni en --card. Og når den `open` så må vi sette borde-left-bottom og borde-rigth-bottom til 0 igjen

2020-12-08 11:23 UTC, HeleneGrini commented on src/business/List/List.stories.tsx
>  export const WithChildren = ({}) => {
Lag gjerne en egen story for expandable, med flere eksempler! Da blir det lettere å søke frem også

2020-12-08 11:25 UTC, HeleneGrini commented
Når du først er i gang med list item --  vil du legge til curser: pointer når den er klikkbar?

2020-12-08 12:08 UTC, mariannemagnussen commented on src/business/List/List.pcss
>      padding: 1.25rem 1.5rem;
ja 💪

2020-12-08 12:33 UTC, mariannemagnussen commented on src/business/List/List.pcss
> +.telia-listItem__mainWrapper {
Focus var ikke helt riktig for list siden den brukte outline. så jeg har byttet den ut til å bruke box-shadow, sånn at den nå har samme stil på focus som de andre komponentene!

2020-12-08 12:34 UTC, mariannemagnussen commented on src/business/List/List.pcss
> +.telia-listItem__mainWrapper {
Også satte jeg border-radius på :

```
&--card {
    border-radius: 0.5rem;
    margin: 0.75rem 0;

    .telia-listItem__mainWrapper:focus {
      border-radius: 0.5rem;
    }
  }
```

2020-12-08 15:49 UTC, HeleneGrini requested changes
Ser bra ut! Den eneste jeg har å pirke på et at compact skeleton ikke har riktig padding. Eller er det good 👍

2020-12-09 09:23 UTC, HeleneGrini approved these changes

2020-12-09 09:48 UTC, merged