Feature/radio btn
TeliaSoneraNorge/styleguide pull request #879
Opened 2021-02-01 13:33 UTC by mariannemagnussen

2021-02-02 06:03 UTC, HeleneGrini requested changes
Maybe rewrite it as a TS component, since we're already working on it? 😊

2021-02-02 06:03 UTC, HeleneGrini commented on src/atoms/RadioButton/RadioButton.jsx
> +        <span className={classnames('radiobutton__text', className ? className : undefined)}>
Vet at ikke det er du som har skrevet denne, men når vi bruker classnames på denne måten så trenger vi ikke sjekker om className er definert

```
 <span className={classnames('radiobutton__text', className)}>

2021-02-02 14:25 UTC, mariannemagnussen commented on src/atoms/RadioButton/RadioButton.jsx
> +      onClick={setChecked ? setChecked : null}
👍

2021-02-02 15:40 UTC, HeleneGrini reviewed
En liten ting 😄

2021-02-02 15:40 UTC, HeleneGrini commented on src/atoms/RadioButton/RadioButton.tsx
> +  children?: React.ReactNode;
Trenger ikke ha med denne nå vi bruker React.FC (den har implisitt children på props)

2021-02-03 06:34 UTC, HeleneGrini approved these changes

2021-02-03 08:34 UTC, merged