Feature/textfield tweaks
TeliaSoneraNorge/styleguide pull request #927
Opened 2021-03-03 12:36 UTC by mariannemagnussen

https://www.figma.com/file/DY2nAi4QVg4DZWQSGP1A0n/Text-field?node-id=2%3A2

Updates:
- Border colors, colors and background-colors
- Paddings 
- Label for compact version
- Help text alignment = right by default

2021-03-03 14:51 UTC, HeleneGrini requested changes
The QuickSearch style is not working with these changes

2021-03-03 14:51 UTC, HeleneGrini commented on src/colors.pcss
> +  --accent-250: #ebebeb;
Må oppdatere der `--medium-light-grey` blir brukt andre steder i css-en

2021-03-03 14:51 UTC, HeleneGrini commented on src/molecules/TextField/TextField.pcss
> +  //  Don't need the commented-out code after a design update on the compact label.
these comments are not allowed in css blocks. Is it working for you? 🤔   should use `/* */` instead

2021-03-04 06:55 UTC, mariannemagnussen commented on src/molecules/TextField/TextField.pcss
> +  //  Don't need the commented-out code after a design update on the compact label.
nope 😅 Forgot to push the last commit 😬

2021-03-04 08:23 UTC, HeleneGrini requested changes
QuickSearch style is still broken

2021-03-04 10:19 UTC, HeleneGrini approved these changes
nais! 😎

2021-03-04 10:19 UTC, merged