Design tweaks on Increment
TeliaSoneraNorge/styleguide pull request #930
Opened 2021-03-04 08:52 UTC by mariannemagnussen

2021-03-04 12:13 UTC, HeleneGrini requested changes
Looks good! small comment regarding the classname

2021-03-04 12:13 UTC, HeleneGrini commented on src/molecules/Incrementer/Incrementer.tsx
> +      className={cn('telia-new', {
`new`?  burde vel fortsatt være `incrementer`?

2021-03-04 21:45 UTC, mariannemagnussen commented on src/molecules/Incrementer/Incrementer.tsx
> +      className={cn('telia-new', {
🙈 absolutt.  Henger igjen fra litt testing 🤓

2021-03-11 09:30 UTC, HeleneGrini approved these changes

2021-03-11 09:30 UTC, merged